### ISSUE TITLE
NPE in KsmCredential when configuration is built using JCasC

### ISSUE THREAD

**Issue by nfalco79** [jenkinsci/keeper-secrets-manager-plugin#28]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
 Jenkins 2.401.1
 configuration-as-code 1647.ve39ca_b_829b_42
 keeper-secrets-manager 1.0-81.vbc31cf2bb5dc
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

I configured a ksm credential in a jenkins instance. After that I download the jenkins configuration using the configuration as code page.
The configuration related to the keeper security manager generated is:
  ```yaml
- ksmCredential:
          allowConfigInject: false
          appKey: "{AQAAABAAAAAQGvDi8J6JJSbg7iwLBAPZRXTpdcxs8tBx6A4Cx4GyhZs=}"
          clientId: "{AQAAABAAAAAQV8woQ23ya+dVvLUgYccFGh75pXSQS+TBlXUWIF7qg40=}"
          description: "123"
          id: "123"
          privateKey: "{AQAAABAAAAAQZZbdRII6ICBlwua6U5CFiNYe3wMll3+hSTCm1+JUkiI=}"
          skipSslVerification: false
```

When jenkins restart (because I updated or install a new plugin) it fails

### Expected Results

Jenkins is able to restart and build KSM credential without error

### Actual Results

Jenkins is no able to restart because a NPE exception in KsmCredential constructor.
[jenkins-0.log](https://github.com/jenkinsci/keeper-secrets-manager-plugin/files/11768961/jenkins-0.log)
